### ISSUE TITLE
Song export

### ISSUE THREAD

**Issue by yaron** [ChristmasTop100/backend-2016#5]
Create something to export all songs, sorted by votes ascending. Can be directly to Spotify(API) or can be copy/pastable.

**Comment by robindrost** [comment]
Lets do this by hand and link to the playlist on spotify.

**Comment by robindrost** [comment]
Zie ook: https://github.com/ChristmasTop100/xmas-top-100/blob/master/app/Console/Commands/SpotifyExport.php
