### ISSUE TITLE
Enable CORS

### ISSUE THREAD

**Issue by dylancom** [ChristmasTop100/backend-2016#7]
"No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access." @yaron

**Comment by yaron** [comment]
Zal later https://github.com/barryvdh/laravel-cors toevoegen, nu even kijken of het met een htacces even snel gefixed kan worden

**Comment by yaron** [comment]
Heb nu de htaccess op prod even aangepast en deze regel toegevoegd:
Header set Access-Control-Allow-Origin "*"
Vanavond kijk ik denk ik even of ik die cors module er ook in kan krijgen en configureren om het beter te fixen.

**Comment by dylancom** [comment]
Top, het werkt nu ieder geval :)

**Comment by yaron** [comment]
Ik heb de cors package toegevoegd aan de backend en dit lijkt nu goed te werken (staat ook op prod). Kan jij nog een controle doen of alles nog klopt? Dan kan deze dicht.

**Comment by dylancom** [comment]
Top,

Alles klopt. 
In de Front-end-2016 repo staat een te testen basis opzet. (Vallend sneeuw + lijstweergave van de beschikbare songs).

npm install && npm start

**Comment by yaron** [comment]
http://christmastop100.nl/
Ziet er goed uit :)

**Comment by dylancom** [comment]
Top,
Heb nog even de fetch url aangepast naar HTTPS (Zag dat het daar nog fout ging op productie)
